### ISSUE TITLE
Normal test mode can give away the answer

### ISSUE THREAD

**Issue by Thra11** [Top-Ranger/harbour-katakana#5]
In normal test mode, the app leaves space for the answer next to the katakana character. This isn't usually a problem, but some of the answers are much longer than others. For example, leaving space for "ji (D-Row)" pushes the character so far over to the left that it's obvious that the answer isn't any of the two character choices.

I'll see about writing a fix that slides the character out of the way only when the answer is shown.

**Comment by Top-Ranger** [comment]
Thanks for the report. I'm sorry that I wasn't able to fix this more quickly, however, I was quite busy over the last weeks. I will push a new release to over the next days.
